# Generated by Django 4.2.4 on 2023-08-12 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establishments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=50, verbose_name='Имя контакта')),
                ('phone', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('phone2', models.CharField(max_length=30, verbose_name='Дополнительный номер телефона')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('working_mode', models.CharField(max_length=50, verbose_name='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='contacts/photo', verbose_name='Фотографии')),
                ('es_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='establishments.establishment')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
